##------------------------------------------------------------------------------
## GitLab CI Go
##
## @author Lars Thoms
## @date   2021-12-15
##------------------------------------------------------------------------------

image: alpine:latest

before_script:
  - apk add --no-cache go upx curl

stages:
  - build
  - upload
  - release

build-go:
  stage: build
  artifacts:
    untracked: true
    expire_in: 1 hour
    paths:
    - public/
  script:
    - go build -ldflags="-s -w" -trimpath hls-subscriber-stats.go
    - upx --brute hls-subscriber-stats
    - mkdir public/
    - mv hls-subscriber-stats public/

upload-go:
  stage: upload
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file "public/hls-subscriber-stats" "${PACKAGE_REGISTRY_URL}/hls-subscriber-stats.x86_64"

release-go:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - |
      release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
        --assets-link "{\"name\":\"hls-subscriber-stats.x86_64\",\"url\":\"${PACKAGE_REGISTRY_URL}/hls-subscriber-stats.x86_64\"}"
